name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install uv
      run: |
        pip install uv
    
    - name: Install dependencies using uv with lock file
      run: |
        uv pip install -e .
        if [ -f uv.lock ]; then
          uv pip sync uv.lock
        fi
    
    - name: Run tests
      run: |
        pytest --cov=rags