name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']

    steps:
    - name: Checkout the repository
      uses: actions/checkout@main
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - name: Sync
      run: uv sync
    - name: Install Pytest
      run: uv pip install pytest pytest-cov pytest-asyncio
    - name: Test
      run: uv run pytest tests/test_retriever.py tests/test_models.py tests/test_utils.py -v
